### ISSUE TITLE
[Services/maker] init should generate the necessary default definition files from go templates

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris#1003]
@zramsay commented on [Tue Oct 04 2016](https://github.com/eris-ltd/eris-services/issues/55)
- [x] remove third party service definition files & Dockerfiles
- [x] keep anything ops related for cli but move to `/hello-eris/dockerfiles`
- [x] have cli generate service definition files & chain/account-type (from cm) using go templates

**Comment by zramsay** [comment]
closed by #1214
