### ISSUE TITLE
[Documentation] Detail porcelain docker throughout stack

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris#1005]
@zramsay commented on [Fri Jul 01 2016](https://github.com/eris-ltd/coding/issues/14)

**Problem:** There is a lot of reverse-engineering needed to tease out some failure with docker (e.g., docker-1.12-rc2 breaks eris, the switch to alpine, etc) ... the overall docker stack integrations are quite complex & IMO, becoming too distant from "here's how you'd do it with `docker run ...`". It's great that we can accomplish in 1-2 commands what would take 10-20 docker commands but _maybe_ things are getting a little out of hand...?

**Solution:** Dockument & maintain separate tests with porcelain docker for a handful of common commands. Some of these once existed in either eris-keys/mint-client...not sure where they went though.

**Comment by zramsay** [comment]
will be so much cleaner/easier to do once cm/pm are in

**Comment by zramsay** [comment]
I no longer see the value in this, and we are winding down (a bit) docker as a dependency anyway
