### ISSUE TITLE
[Compilers] Need to Include More Options for Compilation into Compilers

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris#1078]
Not sure how to nicely do this, but perhaps reading in from a json file on how to do this for the purposes of differentiating based on remappings, optimizations, etc. This will be required with the advent of package management.

**Comment by VoR0220** [comment]
Or we could simply modify the TOML file on the compilers service. The only fields that really matter to us so far insofar as the compilers are concerned are version number and optimization specifications. Something like this should be added to the TOML:

```
[settings]
optimize       = true
optimizeRounds = 500
```

**Comment by zramsay** [comment]
what's the problem/solution?

**Comment by VoR0220** [comment]
Problem: cant formally verify and achieve all potential outputs of compiler

Solution: add them

**Comment by VoR0220** [comment]
This is being closed in favor of the compilers orchestration/version manager thing that is discussed in the RFC
