### ISSUE TITLE
[chains] Show version info in eris chains ls

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris#1126]
Feature request to extend the output of `eris chains ls` with a column that displays the ErisDB version number.
This would help a lot keeping an overview for folks that manage a larger number of chains, especially long-running ones.

Currently, to get this information would be to match the container ID to the output of `docker ps` and deduce the version from the image name (not reliable) or run an `exec` on the docker container to output the version (not convenient).

**Comment by zramsay** [comment]
++, although this is displayed by `eris chains ls -a/--all`, I end up often defaulting to adding the flag manually

**Comment by j-h-scheufen** [comment]
Ah, ok. Then this ticket becomes a change request to move the version info to the default output.

**Comment by zramsay** [comment]
closed by #1196
