### ISSUE TITLE
abi folder not showing up when compiling/deploying multiple contracts in the same file

### ISSUE THREAD

**Issue by fmadotto** [eris-ltd/eris#1130]
- `docker version`: 1.12.1 (on Linux) and 1.12.3 (on Windows)
- `eris version`: 0.12.0 (002c63e) both on Linux and Windows
- `docker-machine version`: 0.8.2, build e18a919 (on Windows)
- operating system details: Windows 7 and Ubuntu 14.04.1

I wanted to compile/deploy a set of contracts on the blockchain, like the ones seen in "The Five Types Model" tutorial. To test things first I tried to compile/deploy two basic get/set contracts in the same file. **The issue is that `eris pkgs do` does not create an `abi` folder** when I try to do that.

* Already tried cleaning up everything with `eris clean -a --chains --dir -i -y` followed by `eris init` with no luck.
* Already tried specifying the compilers with the flag `--compiler https://compilers.monax.io/10114` but anyway, the compilation seems to be executed correctly.

You can find a log with the `-d` flag [here](https://slack-files.com/T1X5D70SC-F3CCVSE76-df8396a33d).

### Steps to reproduce:
1. Set up a simplechain and the folder for the app:
    ```
    $ eris chains make foo
    $ eris chains start foo
    $ mkdir ~/.eris/apps/test
    ```
2.  Put in `test/` this `epm.yaml` file:
    ```
    jobs:

    - name: deployStorageK
      job:
        deploy:
          contract: idi.sol
          wait: true
    ```
    and this `idi.sol` file:
    ```
    contract IdisContractsFTW {
      uint storedData;

      function set(uint x) {
        storedData = x;
      }

      function get() constant returns (uint retVal) {
        return storedData;
      }
    }

    contract IdisContractsFTW2 {
      uint storedData;

      function set(uint x) {
        storedData = x;
      }

      function get() constant returns (uint retVal) {
        return storedData;
      }
    }
    ```
3. Get the address of the full node and launch `eris pkgs do`:
    ```
    eris pkgs do --chain foo --address *full-node-address*
    ```

**Comment by zramsay** [comment]
confirmed bug. Investigating

**Comment by VoR0220** [comment]
the easiest way to resolve this is to label `instance: all`. A better fix is coming down the line. Closing this for now. Reopen if the said fix doesn't work, please.
