### ISSUE TITLE
[Compilers] Push compiler images to docker hub

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris#1179]
Online compilers service utilizes `eris/compilers:vvvvv` rather than `quay.io/eris/compilers:vvvvv`.

The release pipeline needs to have billings push to both quay.io and docker hub for the changes to make it into the online compilers.

**Comment by VoR0220** [comment]
take a look at this when you get the chance: #1166

**Comment by zramsay** [comment]
Issue moved to [eris-ltd/operations #73](https://github.com/eris-ltd/operations/issues/73) via [**ZenHub**](https://www.zenhub.com/)
