### ISSUE TITLE
[tests] Set up travis to better separate test runs around different docker setups

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris#1189]
It's currently unclear to me whether or not Travis does a good job at separating into two jobs for our OS X testing: 1 for docker-machine, the other for Docker for Mac (both of which are readily provided by Travis). If my suspicions are correct, we should rectify this prior to the release so that we get both ends testing on OS X. Same for appveyor.

**Comment by zramsay** [comment]
closed by #1210
