### ISSUE TITLE
Deploying contracts fails on Mac OS & Linux

### ISSUE THREAD

**Issue by NodeGuy** [eris-ltd/eris#1192]
Please include in your bug report:

- [ ] `docker version`

1.13.0, build 49bf474

- [ ] `eris version`

0.12.0

- [ ] `go version` (if applicable)
- [ ] `docker-machine version` (if applicable / !linux)

0.9.0, build 15fd4c7

- [ ] operating system details (osx/windows/linux)

OS X & Linux

- [ ] what you expected to happen

Contract deployment without error.

- [ ] what actually happened

```shell
Error connecting to node (tcp://chain:46657) to get chain id: Post http://chain:46657: dial tcp 198.105.254.228:46657: getsockopt: connection timed out

Could not perform pkg action service: Could not perform pkg action: Container interactive-b4f4914c-6992-4e4d-ac73-16f058f46f0c exited with status 1
```

Also see longer [debug log.txt](https://github.com/eris-ltd/eris/files/739727/debug.log.txt).

- [ ] steps to reproduction

Follow these instructions: https://github.com/eris-ltd/hello-eris/tree/a8d6202ae74ce5c81b3adf95f63db822cadd6741/apps/hello-eris

If issue is a feature request, tell us why this feature is useful.

**Comment by zramsay** [comment]
closing as resolved via discussion on Slack; @NodeGuy confirmed that https://gist.github.com/zramsay/c03c46fbb88ce2aab201632f84776092 worked

**Comment by NodeGuy** [comment]
This bug hit me again while trying to provide support for a customer.
