### ISSUE TITLE
(23) Failed writing body

### ISSUE THREAD

**Issue by Dapco** [eris-ltd/eris#1195]
Please include in your bug report:

- [x] `docker version`
        1.12.5
- [x] `eris version`

- [x] `go version` (if applicable)
        1.7.5
- [ ] `docker-machine version` (if applicable / !linux)
       0.8.2
- [ ] operating system details (osx/windows/linux)
      Raspbian
- [ ] what you expected to happen
      Install eris
- [ ] what actually happened
     (23) Failed writing body
- [ ] steps to reproduction
    
If issue is a feature request, tell us why this feature is useful.

Hi I trying to install eris on Raspbian, but whe I put: "curl https://eris-iot-repo.s3.amazonaws.com/eris-deb/APT-GPG-KEY | sudo apt-key add -
echo "deb https://eris-iot-repo.s3.amazonaws.com/eris-deb raspbian experimental" | sudo tee /etc/apt/sources.list.d/eris.list" the device send this error: (23) Failed writing body.

**Comment by zramsay** [comment]
hi @Dapco our IoT integration is currently out of date and not supported. There are partial instructions in #990 for getting going and you can track progress on re-implementing full IoT integration into `eris` in #1088
