### ISSUE TITLE
Eris connection refused

### ISSUE THREAD

**Issue by test2015deve** [eris-ltd/eris#1204]
Hi, 

I ran command and got the erros as below. Could you help me where i am missing?  Thank you 

sudo su -c "echo deb https://apt.eris.industries xenial main > /etc/apt/sources.list.d/eris.list"
sudo apt-get-update

My code_name ise : Xenial
(cat /etc/*release|grep -i codename)

------------------------------------------------------------------------------------------------------
Error : 

Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Err:5 https://apt.eris.industries ubuntu InRelease
  Failed to connect to apt.eris.industries port 443: Connection refused
Fetched 102 kB in 0s (231 kB/s)
Reading package lists... Done
W: Failed to fetch https://apt.eris.industries/dists/ubuntu/InRelease  Failed to connect to apt.eris.industries port 443: Connection refused
W: Some index files failed to download. They have been ignored, or old ones used instead.
------------------------------------------------------------------------------------------------------

**Comment by zramsay** [comment]
hi @test2015deve 
`apt.eris.industries` no longer exists. I'm curious where you found those install instructions?

From the bottom of `monax.io`, the instructions for linux are:
```
sudo add-apt-repository https://apt.monax.io
curl -L https://apt.monax.io/APT-GPG-KEY | sudo apt-key add -
sudo apt-get update && sudo apt-get install -y eris
```
Please re-open issue if this does not work.

**Comment by test2015deve** [comment]
It is my fault. Everyting is ok now. Thanks for your help
