### ISSUE TITLE
Adding Node to My Eris Blockchain

### ISSUE THREAD

**Issue by test2015deve** [eris-ltd/eris#1207]
Hi,

I have 4 Linux machines which can reach each other on the same network. I have installed separately "docker" and "Eris" , "Eris init" successfully. Now I want to establish a blockchain system which include 4 nodes. I dont where to start to do it. I made some search on the internet and your website and found something but could not do it successfully and a little bit confused.

As Far as I understand, 

First, I will run eris make command on one machine as below
"eris chains make --account-types=Root:1,Full:4 default"

What is Second steps and others? Should I instlall a blockchain on one machine and then transfer the config files the between nodes? Or First transfer config files between nodes and then install a blockchain on nodes.

Could you help me how to continue setup a blockchain which works on 4 nodes?

Thank you for your help

**Comment by zramsay** [comment]
hi @test2015deve the steps are outlined in the [getting started tutorial](https://monax.io/docs/tutorials/getting-started/). The platform walkabout, although a bit dated (some commands have been modified) can be found here: https://youtu.be/S7uXHD2KgtU?t=37m1s

**Comment by test2015deve** [comment]
hi, thanks your help but actually it is not exactly what i need. I passed and used getting started tutorial. I setup a chain successfully. 

My problem is like that; I  made a chain on 1 node by using this command (_**eris chains make --account-types=Root:1,Full:2 testchain**_). 
Now I want to add other nodes to my chain and make connection between my nodes. I guess i should configure related config.files and initialize them respectively. But could not achieve that. How can I do that? Is there any tutorial for adding and installing nodes? 

Note : By the way, the video you sent is beneficial but commands are a bit old like you said.

**Comment by test2015deve** [comment]
Hi, it is solved!
It is just enough to configure config.toml file and start chain by using related profiles. 
Thanks
