### ISSUE TITLE
Error : eris pkgs do --chain fka 

### ISSUE THREAD

**Issue by test2015deve** [eris-ltd/eris#1209]
Hi,

I got the error when ı ran command below. Could you help to solve this? What should i do? Thanks a lot 

**Command :** 
_eris pkgs do --chain chainName --address $addr_

**Error :**
_Deprecation Warning: The use of the 'data' field to specify the name of the contract function has been deprecated. Please update your epm jobs file to utilize a combination of 'function' and 'data' fields instead. See documentation for further details.
Encountered error waiting for event: timed out waiting for event_

**Comment by benjaminbollen** [comment]
Is your chain running? `eris chains ls` presumably so? or missing `$` in `$chainName`?

**Comment by zramsay** [comment]
@test2015deve this means the `data: something` field should be removed from your `epm.yaml`. cc @VoR0220 to confirm

**Comment by VoR0220** [comment]
That's not an error, that's merely a warning. However, there is an error in that you have time out waiting for something to happen. What that is, I do not know without more information. 

To stop that warning from happening, reformat all of your call jobs to the following format:

```
function: myFunctionThatIWantToCall
data: 
   - functionParam1
   - functionParam2
   - functionParam3
```

**Comment by zramsay** [comment]
closing as resolved. @test2015deve if the solution provided by @VoR0220 does not work, feel free to re-open
