### ISSUE TITLE
Calling Smart contract from Node 2 

### ISSUE THREAD

**Issue by test2015deve** [eris-ltd/eris#1226]
Hi,

I have a problem for calling smart contract from Eris node.

I have 2 AWS nodes. 

On Machine 1 :  I ran the commands respectively to make chain
**_eris chains make --account-types=Root:1,Full:2 testchain**
**_eris keys export_**

and move to testchain_full_001 to my node 2 under the sub directory named testchain
Then **_I updated seeds "" in config.toml on machine1 and machine2_** 

And I started chains on nodes as below command;
_**eris chains start fka --init-dir $chain_dir_this**_  
 (Of course, I setted $chain_dir_this with related profiles (eg. full_000, full_001))

At last, _**eris chains logs testchain**_. I can see that nodes can see each other and block heights is rising together.

ALL is OK for now.

Then I wanted to create a smart contract on node 1 by following getting started document on your website and created succesfully.

**_create idi.sol
create epm.yaml
eris pkgs do --chain testchain--address $addr  (of course $addr is set truly)
create package.json
npm install
create app.js and modified it_**

On Node 1 everything is OK. I can call my smart contract.

Here's the my question;

On My node1 I can do everyhting. I want to call my smart contract from **_Node 2_**. 
What should I do to call it from Node 2?

**Comment by compleatang** [comment]
hello @test2015deve & thanks for your question. the contract is propagated to all nodes within the blockchain's network as long as that network has successfully connected. Assuming that your node 2 has connected to node 1 to form a network, then you would run your app.js on node 2 to interact with your contracts from that machine. 

will close this ticket, but feel free to reopen and/or add more information if you cannot successfully run your app.js on node 2.

**Comment by test2015deve** [comment]
hi @compleatang thanks for your reply. 

As far as I understand, no need to create anything on Node2. I just call app.js from Node1 on Node2.
How can I call app.js,which is in Node1, from Node 2 ?

**Comment by compleatang** [comment]
Use the URL for the chain node 2 instead of the URL for node 1 in your app.js.

**Comment by test2015deve** [comment]
Thanks @compleatang 

On Node1; I used **_"Node app.js"_** command to call my contract. 
On node2; I can not use this command. Im a bit confused about what will be the URL. 
Must I create html UI to call?

**Comment by compleatang** [comment]
@test2015deve the easy way to do this is to change your app.js. If you're following along with our tutorial, there will be this line in your app.js:

```js
var erisdbURL = "http://localhost:1337/rpc";
```

Change that line to reference the IP address of node 2 instead of localhost and that will make the javascript layer connect to the smart contracts via your node 2 instead of your node 1.

**Comment by test2015deve** [comment]
I did it ! @compleatang thanks for your help.
