### ISSUE TITLE
[tests] failures to fix for 0.16.0 release

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris#1230]
- `tests/jobs_fixtures/app33-evm_connection_edb_permissions_and_roles_layer` fails on jenkins
- `TestRmChain` fails on appveyor
- `TestLogsTail` fails on appveyor

**Comment by VoR0220** [comment]
? Shouldn't be...unless @benjaminbollen @silasdavis changed something that they shouldn't have?

**Comment by zramsay** [comment]
https://ci.monax.io/job/test_tools-cli-linux-x86-featurebranches/323/console

**Comment by VoR0220** [comment]
odd...will investigate.

**Comment by zramsay** [comment]
replaced by #1262
