### ISSUE TITLE
broken docker install doc link in `eris init` 

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris#1238]
Please include in your bug report:

I am running `Eris CLI Version: 0.12.0 (002c63e)` on Ubuntu 16.04 x64 (at Digital Ocean). I installed Eris via your landing page script:
```
sudo add-apt-repository https://apt.monax.io
curl -L https://apt.monax.io/APT-GPG-KEY | sudo apt-key add -
sudo apt-get update && sudo apt-get install -y eris
```

As I havent installed docker, `eris init` runs me into:
```
# eris init
The marmots cannot connect to Docker. Do you have Docker installed?
If not, please visit here: https://docs.docker.com/installation/linux/

Do you have Docker running? If not, please type [sudo service docker start].
Also check that your user is in the "docker" group. If not, you can add it
using the [sudo usermod -a -G docker $USER] command or rerun as [sudo eris]
```

The link in the second line (https://docs.docker.com/installation/linux/) is broken, I assume it should instead be https://docs.docker.com/engine/installation/linux/.

**Comment by zramsay** [comment]
thanks @SCBuergel this is fixed in #1240
