### ISSUE TITLE
[Files] `--encrypt` flag for eris files

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris#128]
encrypt + dump into ipfs is gonna be a common pattern.

for encryption we could potentially use eris-keys but i think it would be much better to use keybase's soon to be released go library/client. if we can.

**Comment by compleatang** [comment]
moving this to 0.12. i'd like to wait until keybase publishes their (supposedly) upcoming golang app before we worry about this.

**Comment by compleatang** [comment]
unblocked, but keybase always should have been a service.

**Comment by zramsay** [comment]
tech debt & not direction of the platform / has never been requested by a user. it should be up to the specific application to implement this.
