### ISSUE TITLE
[Services] add `auto_docker` to service definition struct

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris#472]
**Problem** -- we are moving in a direction where lots of services (and soon, chains) will need to be operated with a link to a specific docker backend so that they can start and stop containers. Eris need not concern itself with the minuate of what the service|chain says to a specific backend, but it should make it easy to do this (via a `--machine` flag or whatever).

**Solution** -- eris has cognizance of which backend to talk to at runTime. Because of this I think we should make it easy on our users to just say "plug this thing into docker" (`auto_docker = true`). Not with `privileges` of course.

What this would require functionally is that (1) we understand what machine backend we're supposed to hook this service into. Both in terms of DOCKER variables as well as the docker-machine certs -- info which may need to get moved into the Global struct, since we already figure it out in PreRun we may as well pass it up and then just consume the information at a runTime choke point. and (2) figure the most logical place to put this code so it doesn't require too much refactoring (probably in those default setting functions in the loaders). 

This should be a `use with caution` function and therefore require user confirmation before a service is actually hooked into docker but overrideable with a flag and/or env var. As we currently do with pulling.

**Comment by zramsay** [comment]
Not sure I understand the problem...to specify the machine in the servDef file? What it is the solution that `--machine` can't accomplish? The direction we're going in with remotes (well, the one I'm marshalling) would have services remain agnostic of what'll run them while the remoteDefinition file can (but need not) know which services to run on all the hosts. Relatedly, `util.DockerConnect()` is definitely due for a refactor (to use libmachine...and return an error) though it's not clear to me what `do.Service.AutoDocker`'s purpose would be.

**Comment by compleatang** [comment]
Good Q. I think I didn't explain myself clearly. An increasing number of services will themselves need to be hooked into the docker daemon they are running on so that they can themselves start and stop containers. The point of `do.Service.AutoDocker` is to make that simply a bool. So if a service needs to talk to the docker daemon of the machine that it is running on, then it can have:

```toml
auto_docker = true
```

And then when the service is started since eris already knows what docker we are talking to at that moment and whether it will be local or remote for that particular service then it should be able to hook up the service to the daemon. Almost always this would just mean starting the container with:

```go
do.Service.Volumes = append(do.Service.Volumes, "/var/run/docker.sock:/var/run/docker.sock"
```

But perhaps there are other configurations possible.

**Comment by compleatang** [comment]
Now that I think about it, from the container's perspective the only thing we would ever do is mount the volume. But still think having some "shortcut" here will be helpful as more services (and chains of course) need API access to the docker daemon for the machine they're running on.

**Comment by zramsay** [comment]
Ok this make much more sense now. Will have to think through it more though.

**Comment by pietv** [comment]
Mounting a socket is likely not workable on Windows `-v /var/run/docker.sock:/var/run/docker.sock`. 
The alternative I can think of is to set the `DOCKER_HOST` and `DOCKER_CERT_PATH` for the Windows container (mounting the later inside the container from the user machine). Are there any issues with this?

**Comment by compleatang** [comment]
No issues. That's exactly the time of thing we should be normalizing for our users imv. So however we say "connect this service up to my docker engine" is good by me.

**Comment by zramsay** [comment]
do we still want this? are workflows limited without it or is it a "nice to have"?

**Comment by zramsay** [comment]
hasn't been requested as a feature by a customer/user & not really the direction of the platform (less reliance on docker)
