### ISSUE TITLE
[Core] eris init should be able to accept a HTTPSProxy `eris.toml` configuration option for firewalled installations

### ISSUE THREAD

**Issue by rlaveycal** [eris-ltd/eris#505]
I've been trying to install a Ubuntu 14.04 VM to evaluate eris. Install works fine until I get to `eris chains new test` (from https://docs.erisindustries.com/tutorials/getting-started/) when I get an error using 0.11.2.

After trying `eris chains make test` and previous versions of 0.11 I finally got it to work using 0.10.3. It appears that `eris init` doesn't deploy any default configurations (or am I doing something wrong?)

Attached are the listing of my .eris directory after 0.10.3 and 0.11.2 have run. 11.3 looks very sparse.
[eris_10.3.txt](https://github.com/eris-ltd/eris-cli/files/121821/eris_10.3.txt)
[eris_11.2.txt](https://github.com/eris-ltd/eris-cli/files/121822/eris_11.2.txt)

**Comment by zramsay** [comment]
Hi @rlaveycal, the behaviour of `eris init` changed significantly between 0.10.3 and 0.11.2. Can you run `eris init --debug` and paste a link to the gist here.

**Comment by rlaveycal** [comment]
Hi @zramsay ,

I removed my .eris and and ran init followed by chains make, both with debug.

[init.txt](https://github.com/eris-ltd/eris-cli/files/122760/init.txt)
[chainsmake.txt](https://github.com/eris-ltd/eris-cli/files/122761/chainsmake.txt)

**Comment by compleatang** [comment]
Everything looks OK on the init.

The chains make error (which is unhelpful and something we're working on; see #468 and #469 ) is because your keys service is not turned on. To over come this run `eris services start keys` and then rerun the chains make command. If there are any challenges let us know!

**Comment by rlaveycal** [comment]
The problem is that there isn't a keys service installed by default - the .eris/services directory only contains btcd.toml. That's why I had go back to 0.10.3, run init, then install 0.11.2 and do an upgrade. If you look at the 2 directory listings above you'll see that .eris after init by 11.3 contains almost all empty directories.

**Comment by compleatang** [comment]
I'm wondering if this relates to your issue about proxy's in docs repo (which was super helpful, BTW). 

Do you have firewall issues talking to github? All that init does is pull the files from https://github.com/eris-ltd/eris-services and dump them into the services folder. 

Can you try something to debug this?

**Comment by rlaveycal** [comment]
git clone works fine - the above populated .eris/services fine

**Comment by compleatang** [comment]
OK. That should get you started. (You'll also want to clone https://github.com/eris-ltd/eris-chains )

Going to edit the title of this issue as I think we need to be able to accept a proxy value to support init out of the box.

**Comment by rlaveycal** [comment]
I've used the network capture feature of VirtualBox to see what's happening when eris init is running. As surmised _something_ is making a call to raw.githubusercontent.com without using the proxy

```
2458	71.099055	10.0.2.3	10.0.2.15	DNS	136	Standard query response 0x358a A raw.githubusercontent.com CNAME github.map.fastly.net A 185.31.18.133
2460	71.102930	10.0.2.15	185.31.18.133	TCP	74	43601 → 443 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=4294908734 TSecr=0 WS=64
2462	72.105758	185.31.18.133	10.0.2.15	TCP	54	443 → 43601 [RST, ACK] Seq=1 Ack=1 Win=0 Len=0
```

readers.go is the culprit
```
func GetFromGithub(org, repo, branch, path, directory, fileName string, w io.Writer) error {
	url := "https://raw.githubusercontent.com/" + strings.Join([]string{org, repo, branch, path}, "/")
	w.Write([]byte("Will download from url -> " + url))
	return ipfs.DownloadFromUrlToFile(url, fileName, directory, w)
}
```

**Comment by compleatang** [comment]
Yup. Thanks. That confirms my suspicion. We'll add a proxy flag to init to address this scenario.

**Comment by zramsay** [comment]
hi @rlaveycal, I am working on adding a flag for this, however, it looks like it should work out of the box at this time if you `export HTTP_PROXY="http://proxyIp:proxyPort"` see [here](http://stackoverflow.com/a/14663620/5439085) for the reference.

**Comment by zramsay** [comment]
the previous information was incorrect - this did not make the docker client happy. the `--proxy` flag is implemented in the PR above and should make tomorrow's release

**Comment by AFDudley** [comment]
User provided description of issue here:
https://github.com/eris-ltd/docs.erisindustries.com/issues/74

**Comment by zramsay** [comment]
`eris update` doesn't work behind firewall because `git clone` used in each the go update and in the dockerfile of the binary update, hasn't a proxy

**Comment by pietv** [comment]
Respect `http_proxy` and `https_proxy` settings by default, and use `--proxy flag` as an override.

**Comment by pietv** [comment]
Preferring a `HTTPSProxy` configuration setting over the `--proxy` flag so that other potential commands could reuse it and not to overload the command line.

**Comment by zramsay** [comment]
with #1214, we are no longer pulling files from github but rather generating them via templates from the binary. AFAIC Remember, there have been no reported issues of pulling docker images. And with the local compiler by default (#1201), getting the docker images is the only external requirement. Closing as obsolete.
