### ISSUE TITLE
[Chains] `eris chains upgrade/update`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris#563]
wrapper for `mintdump dump/restore`

**Comment by compleatang** [comment]
Process as I understand it:

- [ ] mintdump
- [ ] reset vals heights
- [ ] pull new containers (optional) (or version bump configs)
- [ ] mintrestore
- [ ] turn back on

@ebuchman and @dennismckinnon to confirm

**Comment by zramsay** [comment]
related to #707

**Comment by compleatang** [comment]
0.12.0 is going to be blocking on this issue.

**Comment by zramsay** [comment]
bumping. this won't make it into 0.12.0

**Comment by zramsay** [comment]
duplicate of #707
