### ISSUE TITLE
[Core] Be able to run with debug flag and gist/pastebin the result

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris#704]
**Problem** -- How many times do we say the below when providing support?

> can you rerun with the debug flag please? that will give us a better view. You can pastebin or gist the result.

We say ^ a lot.

**Solution** -- expose a flag something like `--debug-send` which would run the command in debug mode and send all the log output (including the wrapped tooling -- when we're working with tooling -- but not when we're working with things that you just turn on) somewhere. 

Then give the user a handy url to paste into their favorite chat room for someone to "take a look".

**Proposed Strategy** -- leverage Logrus and build a small logrus-pastebin (or logrus-gist) or just this -> https://github.com/johntdyer/slackrus (although the latter two probably require authorization)

**Comment by pietv** [comment]
This can be done with the same functionality Bugsnag is employed in CLI now, just not as an "error", but an "info" event. Debug logs are collected at any time. If, of course, Bugsnag is convenient for this purpose.

**Comment by compleatang** [comment]
Hoped it wouldn't be too hard!

**Comment by zramsay** [comment]
this doesn't seem to really be a problem anymore; users are generally adept at providing debug output ... those that aren't probably won't use the flag.
