### ISSUE TITLE
[Core] Support native (Beta) Docker on Windows

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris#753]
Allow `eris` command line tools to work with [Beta Docker](https://beta.docker.com) on Windows. 

Native Docker for Mac currently works because Docker exposes the standard Unix socket `/var/run/docker.sock` while Docker for Windows doesn't.

Docker client for Windows uses the path `npipe:////./pipe/docker_engine` which `go-dockerclient` currently doesn't seem to support (https://github.com/fsouza/go-dockerclient/issues/531).

Blocking on `go-dockeclient` and looking for a workaround which possibly may not require patching it.

**Comment by zramsay** [comment]
unblocked by https://github.com/fsouza/go-dockerclient/pull/579

**Comment by zramsay** [comment]
update to `go-dockerclient` is long overdue

**Comment by zramsay** [comment]
handled by the #951 epic
