### ISSUE TITLE
[Core] `brew install eris` should not install docker-machine if Docker for Mac exists

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris#814]
things you learn watching other users install eris...

this'll block until the Docker for Mac issues get sorted (eg. #780, #767 #753(ish))

**Comment by pietv** [comment]
Homebrew will likely keep using the `docker` binary which doesn't include virtualization paraphernalia which may still require `docker-machine` (for a while...), but if a user has docker installed already, it shouldn't try to install `docker-machine`. :+1:

**Comment by zramsay** [comment]
handled by the #951 epic
