### ISSUE TITLE
[Pkgs] `eris pkgs` improvements drawing board

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris#831]
Discussion:
1. Removing `import` and `export` commands (#823) will leave `do` the only `pkgs` command — let's rename it to `run` as in `eris run contract.sol` making both the `run` command shorter as it is the most important command of the `eris` tooling and making it feeling simpler / easier to find without reading docs.
2. Make the `epm.json` file dumping its output to stdout by default
3. Figure the address for `eris pkgs do|eris run` command automatically by the chain name, making the address specification redundant.
4. Consider simplifying `epm.yaml` file by not mentioning file or job names / using an alternative / simpler file format.
5. Consider combining `epm.json` file with ABI files (which are both in JSON format).

**Comment by VoR0220** [comment]
1. Agree

2. Which issue is this referencing?

3. 👍 
4.  What would be an alternative to file or job names? I'd love to hear suggestions.

5. Which issue is this referencing?

**Comment by pietv** [comment]
@VoR0220 #2 and #5 there are no issues, these are just thoughts on simplifying the running contracts command if feasible / sensible.

#4: yeah, if the job names can be derived from the `.sol` file itself, along with filenames maybe (as Java's source files are named after the class name)... anything to make the `epm.yaml` file simpler. 

Also this: #727 (possible not to use `epm.yaml` file at all).

**Comment by zramsay** [comment]
see https://github.com/eris-ltd/eris-cli/pull/786 && .... (can't findthe PR/branch i thought i'd made for that PR)

**Comment by zramsay** [comment]
for 5., see https://github.com/eris-ltd/eris-pm/issues/176, which will simplify names a bit. @VoR0220 did mention the other night that the directory from where we run `eris pkgs do` needs to be better organized, but i think we should hold off on that until the new features are in

**Comment by compleatang** [comment]
1. we'll have more functionality here. For now let's leave it as `eris pkgs do`

2. let's leave the output as is, but we need to return that buffer from the container and populate to stdout along `with` the container rather than after container exits. 

3. Indeed. Relates to #759 and #886 

4. That will be a challenge. Let's get more user feedback first.

5. Solid idea, but will have big implications for both the js libs and the rest of the system.

**Comment by zramsay** [comment]
this is captured well-enough in the various specific issues. Priorities are set by the products team cli co-ordination ticket
