### ISSUE TITLE
[Core] Change default compilers to a local compiler

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris#854]
**Problem(s)** -- we currently default to the eris compilers' service. While we do not track user's IP addresses nor do we cache their code for more than a day, it is not ideal situation that users who want increased privacy or do not have access to the internet have such a usability issue with what the default of `eris pkgs do` is. 

**Solution** -- change the default for `eris pkgs do` from the current eris compilers service to a local one. The functionality for easily starting and linking a local compiler was shipped in #840 but the functionality is not currently default. 

There are two issues which are blocking  this change from happening are: https://github.com/eris-ltd/eris-compilers/issues/79 and #851 . Once both of those are shipped then this issue is ready to be addressed.

**Comment by zramsay** [comment]
closed by #1201
