### ISSUE TITLE
[Pkgs] --contracts-path deletes the directory specified for --contracts-path upon failure

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris#904]
moved from https://github.com/eris-ltd/eris-pm/issues/197, related to https://github.com/eris-ltd/eris-pm/issues/196

**Comment by zramsay** [comment]
this bug needs to be ferreted out / tested in #900

**Comment by j-h-scheufen** [comment]
Adding the problem description from ticket https://github.com/eris-ltd/eris-pm/issues/196. The ticket is regarded as closed when the described setup is possible.
-----------

Given the following directory and contract setup:

/users/X/workspace/project/ => root
$root/contracts/Mappings.sol
$root/contract_bundles/erisindustries/common-base/BaseErrors.sol
$root/test/fixtures/MappingLib/epm.yaml

The epm.yaml has the following content:

jobs:
- name: BaseErrorsLib
  job:
    deploy:
      contract: contract_bundles/erisindustries/commons-base/BaseErrors.sol
      wait: true

- name: MappingsLib
  job:
    deploy:
      contract: contracts/Mappings.sol
      libraries: BaseErrors:$BaseErrorsLib
      wait: true

The MappingsLib.sol contains an import statement:
import "contract_bundles/erisindustries/commons-base/BaseErrors.sol";

The following command is executed with the $root project folder as the start directory to look for contracts:

eris pkgs do -c test -a CDB00407B6EDBF6735A88AA5B34FA24A8984D421 -l http://172.17.0.2:9099 -p "/Users/X/workspace/project"
Performing action. This can sometimes take a wee while.
Executing Job                                 defaultAddr
Executing Job                                 BaseErrorsLib
Deploying Contract                       name=BaseErrors
                                         addr=EFEB89F134AD375A0F8FEBB138B928788085CE96
Executing Job                                 MappingsLib
failed to read include file open contracts/contracts/contract_bundles/erisindustries/commons-base/BaseErrors.sol: no such file or directory
ERR!:Failed to read include file: open contracts/contracts/contract_bundles/erisindustries/commons-base/BaseErrors.sol: no such file or directory
Error compiling contracts
:65:20: Error: Undeclared identifier.
            return BaseErrors.RESOURCE_ALREADY_EXISTS();
                   ^--------^

As can be seen, the paths in the epm.yaml are resolved correctly using the $root project dir as starting point. Both .sol files are found for deployment.
However, the import statement inside the Mappings.sol file results in an unexpected path assembly and error:
open contracts/contracts/contract_bundles/erisindustries/commons-base/BaseErrors.sol: no such file or directory

**Comment by VoR0220** [comment]
closing in favor of #1166

**Comment by zramsay** [comment]
This is a specific bug that can be since independently of the compilers refactor

**Comment by VoR0220** [comment]
The issue is already been documented in the consolidated issue #1166 . That issue is not a compilers or packages specific issue, it is both. Its a planned series of steps along with solutions to address each problem and therefore takes priority.

**Comment by VoR0220** [comment]
Recommend closing.

**Comment by zramsay** [comment]
I'll pick this up for 0.16.1

**Comment by zramsay** [comment]
we've just discussed this on the weekly call. Although this issue reads like a bug, it represents a more serious design flaw described in #1166. closing in favour of that
