### ISSUE TITLE
[Services] Harmonize stack treatment of keys and compilers

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris#927]
**Problem** -- currently we rely on the keys and compilers to (partially) utilize service definition files. This is all well and good at the beginning. However, at this time, the keys service and the compilers service are currently treated quite differently. On `init` the keys service will have its image overwritten to utilize the current stack version (which is good). However, the compilers still are utilizing the `latest` tag. However, now that we are integrating the `--local-compilers` flag and also iterating towards local compilers by default, we need to harmonize how we treat these two services which we build. 

**Solution** -- i'm not 100% sure the best way to address this. 

_Option A:_ On the one hand keeping treatment of keys and compilers via service definition files _does_ help users be able to easily modify how the services boot. The lowest cost treatment is to write the proper compilers image tag on init similarly to how we currently handle keys **and** to refactor the service definition file so that those ports are _not_ exported (to reduce possible port conflicts and such). 

_Option B:_ On the other hand, part of me feels that we should just be opinionated and get keys and compilers out of the way for users. We can do this by setting up default keys and compilers structs in either definitions or another appropriate package, and then populate those structs and pass them directly to perform in one fell swoop whenever the appropriate chain or service or tool needs the service to be on. This Option B would reduce our surface area and increase our test precision quite significantly (it would also be easier to mock for proper unit testing).

**Comment by zramsay** [comment]
this is handled by @VoR0220's compilers version manager RFC
