### ISSUE TITLE
[Pkgs] Harmonize treatment of compilers

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris#928]
**Problem**  -- currently our handling of the compilers is ad hoc (at best). We have a compilers endpoint and port we keep in the global config, we have the compilers service definition file, we have the default eris compilers service, and we have the local compilers flag. Within pkgs/operate.go there is a mismatch (because of quick patches leading to techDebt) of how `do.Compilers` is populated. (This problem is related somewhat to #927 ).

**Solution** -- the probable solution is to remove the compilers population from `pkgs` at all. All that functionality should likely be moved to `util` and have the treatment harmonized. The decision tree should likely be as such:
- if `--local-compilers` flag -> boot and link local compilers
- else if `--compilers` flag -> utilize url:port of given flag
- else -> utilize global default populated in eris.toml

Note that when we move to local compilers being the default then the decision tree would be as such:
- if `--compilers` flag -> utilize url:port of given flag
- else if `--remote-compilers` flag -> utilize global default populated in eris.toml (using companies may want to run a harmonized compilers service behind their firewall to ensure that all compiled contracts are kept in one place for IP security reasons; such a flag would enable this)
- else -> boot and link local compilers

Final point is that when we move to local compilers by default we may want to have a global setting in eris.toml that identifies whether we should utilize the local or the remote compilers by default if no flags are given. I can see a clear use case where a harmonized (remote) service is what using companies will want their developers to utilize.

**Comment by VoR0220** [comment]
closing in favor of compilers orchestration/version manager thing discussed in RFC
