### ISSUE TITLE
[Chains] if no moniker is given (or if the default is read) -> enforce a unique moniker

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris#995]
@compleatang commented on [Sun Mar 20 2016](https://github.com/eris-ltd/eris-db/issues/80)

perhaps using docker's container names algo ...? 

---

@compleatang commented on [Thu Oct 13 2016](https://github.com/eris-ltd/eris-db/issues/80#issuecomment-253383956)

this should be on the cli side as it is a runtime consideration.

**Comment by compleatang** [comment]
This issue is logged, but it should be blocked until we have an agreed pathway for the following actions:

- network boot;
- joining a network; and
- upgrading a network

Solving those involves having a longer discussion which work on this issue will block on finalizing.

**Comment by compleatang** [comment]
Ref -> https://github.com/eris-ltd/eris-db/issues/294

**Comment by zramsay** [comment]
With consolidation, moniker now takes on the name of the account for that node:
```
eris chains make marmot --account-types=Full:1,Developer:2
cat ~/.eris/chains/marmot/marmot_developer_001/config.toml
```
=> `moniker = "marmot_developer_001"`
