### ISSUE TITLE
[Compilers] `/healthz` endpoint - define introspective health check endpoint - "Yes, I'm alive!"

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris#996]
@zramsay commented on [Mon Aug 08 2016](https://github.com/eris-ltd/eris-compilers/issues/80)

**Problem:** Compilers are often down/not working which causes problems for several users (e.g. https://github.com/eris-ltd/eris-cli/issues/856)

**Solution:** A `/healthz` endpoint that run through some tests internally & ensures contracts can compile. This lets anyone "check that the compilers are up and will work" without having to send any contracts for compilation.

---

@SCBuergel commented on [Mon Aug 08 2016](https://github.com/eris-ltd/eris-compilers/issues/80#issuecomment-238201361)

Why not ship a compiler along with the eris binary and compile locally by default? This would prevent such issues in the first place and additionally be way more user-friendly in that I do not need to have internet connection to compile my contracts or setup a compiler myself.

---

@compleatang commented on [Mon Aug 08 2016](https://github.com/eris-ltd/eris-compilers/issues/80#issuecomment-238201861)

We're working in that direction. It should be done by 0.12.1 release. 0.12.0 official will have a `--local-compiler` flag that will manage everything. This issue is where we're working off of -> https://github.com/eris-ltd/eris-cli/issues/854

**Comment by compleatang** [comment]
eris-compilers issues will now be tracked in this repository.

**Comment by zramsay** [comment]
similar to https://github.com/eris-ltd/eris-db/issues/153

**Comment by VoR0220** [comment]
closing in favor of compilers orchestration/version manager thing discussed in RFC
